services:
  router:
    container_name: apollo_router
    build:
      context: .
      dockerfile: Dockerfile
    image: my-custom-router:v2.9.0
    ports:
      - "80:4000"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ""
    command:
          - "/bin/sh"
          - "-c"
          - |
            # Генерируем граф
            APOLLO_ELV2_LICENSE=accept rover supergraph compose --config ./subgraphs.yaml > supergraph.graphql && \
            # Запускаем роутер с ВАШИМ конфигом (/app/router.yaml)
            /dist/router --config /app/router.yaml --supergraph supergraph.graphql --dev
    networks:
      - federation_net

networks:
  federation_net:
    external: true