services:
  router:
    container_name: apollo_router
    build:
      context: .
      dockerfile: Dockerfile
    image: my-custom-router:v2.9.0
    ports:
      - "80:4000"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ""
    command:
      - "/bin/sh"
      - "-c"
      - |
        APOLLO_ELV2_LICENSE=accept rover supergraph compose --config ./subgraphs.yaml > supergraph.graphql && \
        /dist/router --config /dist/config/router.yaml --supergraph supergraph.graphql --dev
    networks:
      - federation_net

networks:
  federation_net:
    external: true