services:
  router:
    container_name: apollo_router
    image: ghcr.io/apollographql/router:v2.9.0 # Используем свежую версию
    ports:
      - "80:4000"
    volumes:
      - ./supergraph.graphql:/dist/schema/supergraph.graphql
      - ./router.yaml:/dist/config/router.yaml
    # ДОБАВИЛИ "--dev" В КОНЕЦ СПИСКА:
    command: 
      - "--config" 
      - "/dist/config/router.yaml" 
      - "--supergraph" 
      - "/dist/schema/supergraph.graphql"
      - "--dev" 
    networks:
      - federation_net
    deploy:
      replicas: 1 # Для локалки хватит 1

networks:
  federation_net:
    external: true